### ISSUE TITLE
Exception raise ZeroDivisionError

### ISSUE THREAD

**Issue by MadRabbit05** [pyutils/line_profiler#100]
Hi,

Exception is raised if profiled function do nothing (just pass). I agree that function useless should not be present or profile.
But if you decide to profile in a single shoot a lot of functions, some stub function may be present in package.
```
File "/opt/anaconda3/envs/XXXXXX/lib/python3.8/site-packages/line_profiler.py", line 228, in show_func
    '%5.1f' % (100 * time / total_time) )
ZeroDivisionError: float division by zero
```

with that part of code : 
```
from line_profiler import LineProfiler
lprofiler = LineProfiler()

for function in functions:
    lprofiler.add_function(fonction)

lp_wrapper = lprofiler(mainProfile)
lp_wrapper()

lprofiler.print_stats()
```

Thanks for that package :-)
MadRabbit

**Comment by Nodd** [comment]
I can't reproduce this bug. Can you provide an example of a function that does nothing, and which OS ou use ? I tried :

```python
@profile
def dummy1():
    pass

@profile
def dummy2():
    """docstring"""

@profile
def dummy3():
    return
```
But all of them give me non-zero time for the last line. I tried on Windows with python3.9.

**Comment by Nodd** [comment]
Update: I got the problem while running tests in Linux in Nodd/lineprofilergui@09ed262428ff7da164bb2025bc6a1ee82333c5eb. Maybe it has something to do with timer precision.
Anyway, it needs fixing, either by displaying NaN or an empty value.

**Comment by Nodd** [comment]
Sure, that was my intention.
Which solution do you prefer, display a NaN or an empty string instead of the percent value ?

**Comment by Erotemic** [comment]
I would personally go for NaN, but either solution sounds fine to me.

**Comment by MadRabbit05** [comment]
percent=0 stands for "function ran in 0% of total_time".
Function ran in eps seconds so the percent computed is total_time/eps (so egal to 0 with the rounding format)

NaN could be more for "profiled function" unused in code (I do not know if it is possible).
