### ISSUE TITLE
Could not find source code file when running in Jupyter lab

### ISSUE THREAD

**Issue by aeryen** [pyutils/line_profiler#101]
Maybe it's me being silly but.

Symptom:
when running in jupyter lab the following command
%lprun -f some_function some_function()
```
Timer unit: 1e-06 s

Total time: 0.72679 s

Could not find file /tmp/xpython_38521/3689601706.py
Are you sure you are running this program from the same directory
that you ran the profiler from?
Continuing without the function's contents.

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    29                                           
    30         1          3.0      3.0      0.0  
    31                                           
    32         1        167.0    167.0      0.0  
    33         1         97.0     97.0      0.0  
```

So essentially it can't find a corresponding .py source code to match function content.

My environment is 
ipykernel           6.4.0
ipython             7.27.0
jupyter-client      7.0.2
jupyter-core        4.7.1
jupyter-lsp         1.4.1
jupyter-server      1.11.0
jupyterlab          3.1.11
jupyterlab-lsp      3.8.1
jupyterlab-pygments 0.1.2
jupyterlab-server   2.8.1
jupyterlab-widgets  1.0.1
line-profiler       3.3.0

I'm using XEUS-Python 3.8, I've also tested with the regular ipykernel Python 3.8, also doesn't work.

The folder it's attempting to find, /tmp/xpython_38521 is not created in the first place.
However I notice that if i turn on jupyter lab debug mode , the folder will show up but the .py file is still not there.

I think yesterday when i first time used lprun it worked once!
However some how 5min later it stopped working.

**Comment by aeryen** [comment]
I've tested a few more and try to make this replicable.
Reinstalled brand new miniconda, new virtual env, and tested in both jupyter-lab and jupyter-notebook.
process:

1. Install latest miniconda
https://docs.conda.io/en/latest/miniconda.html

2. follow xeus-python instruction to install latest env
https://github.com/jupyter-xeus/xeus-python
conda install xeus-python notebook -c conda-forge

3. install jupyter-lab and line-profiler

4. profile with following
```
%load_ext line_profiler

def my_method():
    for i in range(20):
        print( "" + str(i) )

%lprun -f my_method my_method()
```

**Comment by Erotemic** [comment]
It might be the same as https://github.com/pyutils/line_profiler/issues/86 which was just published in 3.3.1. Try updating and check if your issue is fixed.

**Comment by aeryen** [comment]
> It might be the same as #86 which was just published in 3.3.1. Try updating and check if your issue is fixed.

The latest version 3.3.1 really does fixed it! Thanks!

However it still doesn't work very well with xeus-python, which seems to be less of an issue now that jupyter can debug using regular ipykernel. 
But just in case you folks plan to support xeus, i'm guessing the issue is simply in this line:
https://github.com/pyutils/line_profiler/blob/3994c2a05d6f45c159b6e24aa8647cf60f7d2049/line_profiler/line_profiler.py#L203

The xeus-python's temp folders are named like: /tmp/xpython_43854/72582958.py

**Comment by Erotemic** [comment]
@aeryen Feel free to make a PR adding that check. I'm glad to unofficially support xeus if it is just a one line change (I really don't know much about what it is, I suppose a C++ re implementation of Jupyter?).

**Comment by aeryen** [comment]
Hi thanks for letting me do that! I've just made a PR with one line change.
This is my first PR so let me know if i messd up somewhere!
