### ISSUE TITLE
Citing for academic work

### ISSUE THREAD

**Issue by mnicstruwig** [pyutils/line_profiler#111]
Hi there,

I'm currently writing my postgraduate thesis, where the `line_profiler` and `kernprof` tools proved instrumental (pun not intended) in making some of my work tractable, by identifying slow portions of the code. As I briefly discuss using these tools in my thesis, I'd like to provide a citation / reference so that future readers can also access these tools. 

Is there a preferred citation somewhere (I tried some cursory googling to no success) that you'd prefer I use?

Thanks for maintaining a fantastic tool!

**Comment by Erotemic** [comment]
Here is a bibtex entry I came up with: 

```
@misc{line_profiler_331,
  author       = {Kern, Robert and others},
  title        = {Line Profiler and Kernprof},
  url          = {https://github.com/pyutils/line_profiler},
  version      = {3.3.1},
  date         = {2021-09-24},
  howpublished = {Github},
}
```

I don't have strong opinions on the topic of formatting details, as long as the basic information is included (Robert Kern as the main author, the name of the library, and a URL) that should be sufficient for someone to search up the reference.

Of course, if @rkern has any opinion, please defer to that.

**Comment by rkern** [comment]
That would be fine with me as well.

**Comment by mnicstruwig** [comment]
Perfect, thank you.

Also, thanks for the wonderful tool and maintenance!
