### ISSUE TITLE
Direct importation of line_profiler's output

### ISSUE THREAD

**Issue by alisheikholeslam** [pyutils/line_profiler#117]
Hello,

I have posted [an issue in TAMPPA repository](https://github.com/pra-dan/TAMPPA/issues/2) relating to importation of the line_profiler's output, which was outputted by `lp.dump_stats("mem_res_1.txt")`, into TAMPPA `mem_parse`. The problem is well described in that [TAMPPA issue](https://github.com/pra-dan/TAMPPA/issues/2) and have links to check if it is needed. I know that it could be imported from console as it is mentioned by @rkern in [ex line_profiler's repository](https://github.com/rkern/line_profiler/issues/178). But I would like to know if it could be imported and decoded without any problem to be used in TAMPPA and …, directly. I took such a thing from the [**rkern**'s answer](https://github.com/rkern/line_profiler/issues/178) that it is not considered to be imported directly. If so, I would be appreciated for explaining the reason. I didn't find any solution or encoding appropriate for solving this issue. Is there any specific encoding for that?

**Comment by rkern** [comment]
It's just a [pickled](https://docs.python.org/3/library/pickle.html) [`LineStats` object](https://github.com/pyutils/line_profiler/blob/main/line_profiler/_line_profiler.pyx#L86-L101). Just [unpickle it](https://github.com/pyutils/line_profiler/blob/main/line_profiler/line_profiler.py#L383-L388).

**Comment by Erotemic** [comment]
For a working example, I have a wrapper for `line_profiler` in my xdev package: https://github.com/Erotemic/xdev/blob/main/xdev/profiler.py that demonstrates how I've used `line_profiler` in Python code.

When I want to profile a function once I use `xdev.profile_now`, which dumps stats to stdout every time the wrapped function is called.

```
In [3]: def test_arithmetic_ops():
   ...:     int_num = 3210
   ...:     float_num = 432.0
   ...:     for i in range(1000):
   ...:         d1 = int_num * i
   ...:         d2 = int_num + i
   ...:         d3 = int_num - i
   ...:         d4 = int_num / (i + 1)
   ...: 
   ...:         f1 = float_num * i
   ...:         f2 = float_num + i
   ...:         f3 = float_num - i
   ...:         f4 = float_num / (i + 1)
   ...: 
   ...: 
   ...: if __name__ == '__main__':
   ...:     import xdev
   ...:     xdev.profile_now(test_arithmetic_ops)()
   ...: 
Timer unit: 1e-06 s

Total time: 0.00622 s
File: <ipython-input-3-60957bb34ee1>
Function: test_arithmetic_ops at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     1                                           def test_arithmetic_ops():
     2         1          1.0      1.0      0.0      int_num = 3210
     3         1          1.0      1.0      0.0      float_num = 432.0
     4      1001        634.0      0.6     10.2      for i in range(1000):
     5      1000        646.0      0.6     10.4          d1 = int_num * i
     6      1000        661.0      0.7     10.6          d2 = int_num + i
     7      1000        662.0      0.7     10.6          d3 = int_num - i
     8      1000        828.0      0.8     13.3          d4 = int_num / (i + 1)
     9                                           
    10      1000        668.0      0.7     10.7          f1 = float_num * i
    11      1000        693.0      0.7     11.1          f2 = float_num + i
    12      1000        682.0      0.7     11.0          f3 = float_num - i
    13      1000        744.0      0.7     12.0          f4 = float_num / (i + 1)
```

**Comment by alisheikholeslam** [comment]
> When I want to profile a function once I use `xdev.profile_now`, which dumps stats to stdout every time the wrapped function is called.

@Erotemic It seems, your codes is equivalent to `lp.print_stats()` for showing the results, but in a better writing style. What is the difference?

My question is about reimporting the outputted file, which is outputted by `lp.dump_stats`, as a readable file for TAMPPA  `mem_res`. There is no problem when I am using console for outputting e.g. by writing something like `python file.py > mem_res_1.txt` and … . The problem is relating to that one which was outputted without console. When it is imported, it could not be readable by `mem_res` and may need to decode or … [as the issue that I have explained before](https://github.com/pra-dan/TAMPPA/issues/2). The main question is what is the difference between console and `lp.dump_stats` outputs? and how to import and prepare the `lp.dump_stats` output file to be the same as console one (to be readable by TAMPPA).

**Comment by alisheikholeslam** [comment]
> It's just a [pickled](https://docs.python.org/3/library/pickle.html) [`LineStats` object](https://github.com/pyutils/line_profiler/blob/main/line_profiler/_line_profiler.pyx#L86-L101). Just [unpickle it](https://github.com/pyutils/line_profiler/blob/main/line_profiler/line_profiler.py#L383-L388).

I have seen it before that `line_profiler` pickled the results by `HIGHEST_PROTOCOL`, but could not use it. As I have unpickled that, it gets `<line_profiler._line_profiler.LineStats at 0x7f3b934e6e10>` which I don't know how to read and convert it as an appropriate one. How to import and prepare the `lp.dump_stats` output file to be the same as console one, after importation (to be readable by TAMPPA).

**Comment by rkern** [comment]
[Here's the code that prints the text representation of `LineStats`](https://github.com/pyutils/line_profiler/blob/main/line_profiler/line_profiler.py#L168-L245), for your reference. Instead of printing out each row, put the data into the [`DataFrame` that TAMPPA wants](https://github.com/pra-dan/TAMPPA/blob/master/tamppa/tamppa_code_tim.py#L47).

**Comment by pra-dan** [comment]
Hi @alisheikholeslam 

The issue stays the same: TAMPPA lacks any interface to accept pickle files as input, or this would have been simple. In the meantime, TAMPPA is updated, you can try this sor-of hack which suits your usecase.
```python3
from line_profiler import LineProfiler
from line_profiler import show_text, load_stats

import os
import random
import sys
from tamppa import mem_parse

# delete if any similar file occurs, to avoid overwriting
try:
    os.remove('a.txt')
except OSError:
    pass
 
# Redirect stdout to our log dump file
stdout = sys.stdout # keep a local copy to reset it in the end
sys.stdout = open('a.txt','w')

def do_stuff(numbers):
    s = sum(numbers)
    l = [numbers[i]/43 for i in range(len(numbers))]
    m = ['hello'+str(numbers[i]) for i in range(len(numbers))]

numbers = [random.randint(1,100) for i in range(1000)]
lp = LineProfiler()
lp_wrapper = lp(do_stuff)
lp_wrapper(numbers)

# Dump results
lp.dump_stats("mem_res_1.pkl")

# Parse results 
lstats = load_stats("mem_res_1.pkl")
show_text(lstats.timings, lstats.unit)
# close stream
#sys.stdout.close()

# allow TAMPPA to process txt dump file
## reset stdout
sys.stdout = stdout
mem_parse('a.txt')

sys.stdout.close()
````

Hope it helps :)
