### ISSUE TITLE
ModuleNotFoundError when reading profiler file 

### ISSUE THREAD

**Issue by HeyItsBethany3** [pyutils/line_profiler#128]
Hi, 
I'm following the instructions but when I run the command
```python -m pipeline.py.lprof``` to read the profiler file, I'm getting the error below:

```Error while finding module specification for 'pipeline.py.lprof' (ModuleNotFoundError: No module named 'pipeline.py'; 'pipeline' is not a package)```

Thank you for your help!

**Comment by Erotemic** [comment]
You forgot the `pstats`. The instruction in the README is:

```
$ python -m pstats script_to_profile.py.prof
```

**Comment by HeyItsBethany3** [comment]
Ahh okay thank you! 
I am using this command now, but I keep getting the error ```No statistics object is loaded.```. Do you have any advice on this?

I am using this guide: https://www.stefaanlippens.net/python_profiling_with_pstats_interactive_mode/

Thank you

**Comment by HeyItsBethany3** [comment]
@Erotemic Do you have any advice for this? Thank you so much!

**Comment by Erotemic** [comment]
Without a minimal working example, there is little further I can do to diagnose. I suggest carefully re-following the tutorial and if it still isn't working, make a minimal working example that demonstrates the problem.
