### ISSUE TITLE
How do you feel about move the project to pythonprofilers organization?

### ISSUE THREAD

**Issue by espdev** [pyutils/line_profiler#14]
Hi everyone,

There is an organization: https://github.com/pythonprofilers

Currently, the organization contains [memory_profiler](https://github.com/pythonprofilers/memory_profiler) package that is inspired by line_profiler.

It seems to me it would be nice to gather all these profiling tools within one organization.

Also, how do you feel about disconnect this fork from parent project and make it an independent project repository (with preserving the history of commits)?

**Comment by Erotemic** [comment]
On the first part, I'm hesitant to move the repo to another organization, especially one that only has one other package. I put a fair amount of effort into setting this one up and ironing out details like auto-publishing gpg-signed packages to pypi.  I'm not strictly against it, but I don't want to have to redo all of that work. For now I'm going to decline, but I might reconsider if you can show me other python profiler projects that might be willing to consolidate there. 

That being said, I would be willing to add a "related projects" section to the README and link to memory_profiler or other similar python tools. If you create that PR I'll accept it. 

As far as disconnecting the fork from the parent repo, I'd actually like to do that. Its a bit annoying that new PRs always target the original repo. However, I didn't see an easy way to make that happen. I think it would involve deleting and then re-creating the repo. If you know an easy way to do this let me know.

**Comment by espdev** [comment]
@Erotemic 

Thanks for your answers! I understand that you have done a great job and move the project to another organization now would not be convenient and senselessly for you. I agree.

As far as disconnecting the fork, when the project becomes independent, the GitHub fork mechanism becomes inconvenient for development (PRs always target the original repo, contributing to the fork statistics are not taken into account and other things).

> However, I didn't see an easy way to make that happen. I think it would involve deleting and then re-creating the repo. If you know an easy way to do this let me know.

When the repo is already created as a fork it cannot be disconnected from the parent project via GitHub public interface. GitHub help contains the instructions only for [duplicating a repository](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository).

However, I found the following question on SO: https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

> You can contact github support and ask them to switch your repository to "normal mode".
>
> On this page, "Commit was made in a fork" paragraph, it is explained that one has to go through support to switch. Therefore, it is likely that there is no way to do that by yourself (unless you destroy and recreate your repo which is explained before... if you do so be careful if you have tickets or a wiki attached to your project as they will be deleted!).

**Comment by espdev** [comment]
I see that the repository has become independent. Wow!

I will try to make PR with adding "related projects" section to the README and link to memory_profiler soon.

Thanks!
