### ISSUE TITLE
Missing `sdist`s on PyPI

### ISSUE THREAD

**Issue by jakirkham** [pyutils/line_profiler#148]
Looks like releases `3.5.0` and `3.5.1` didn't include `sdist`s on PyPI. Appears `3.4.0` is the last release that has an `sdist` on PyPI. Would it be possible to push `sdist`s for these releases?

**Comment by Erotemic** [comment]
Yes, I'll get those pushed up. Probably will have to wait until the 26th or 27th. Not sure why the automated script didn't do it, but I'll manually take care of it.

**Comment by jakirkham** [comment]
Thanks Jon! 🙏

**Comment by Erotemic** [comment]
Should be up now:

https://pypi.org/project/line-profiler/3.5.1/#files
https://pypi.org/project/line-profiler/3.5.0/#files

**Comment by jakirkham** [comment]
Great thanks Jon! 😀
