### ISSUE TITLE
Can't install on python3.8.2, both pip and wheel are of the latest version

### ISSUE THREAD

**Issue by ToffeeNeko** [pyutils/line_profiler#15]
ERROR: Failed building wheel for line-profiler
Failed to build line-profiler
ERROR: Could not build wheels for line-profiler which use PEP 517 and cannot be installed directly

**Comment by sfcaracciolo** [comment]
Same issue on python 3.7.5-amd64

**Comment by ToffeeNeko** [comment]
> Same issue on python 3.6.8-amd64

Solved by installing an offline package, you can find it here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#line_profiler

Hope this helps.

**Comment by sfcaracciolo** [comment]
> 
> 
> > Same issue on python 3.6.8-amd64
> 
> Solved by installing an offline package, you can find it here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#line_profiler
> 
> Hope this helps.

Thanks a lot. Works! :)

**Comment by yougeyxt** [comment]
Same issues here.

**Comment by adir1661** [comment]
> > Same issue on python 3.6.8-amd64
> 
> Solved by installing an offline package, you can find it here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#line_profiler
> 
> Hope this helps.

after running this whl file i still get 
`'kernprof' is not recognized as an internal or external command
`

**Comment by ToffeeNeko** [comment]
> > > Same issue on python 3.6.8-amd64
> > 
> > 
> > Solved by installing an offline package, you can find it here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#line_profiler
> > Hope this helps.
> 
> after running this whl file i still get
> `'kernprof' is not recognized as an internal or external command `

You shouldn't 'run' the .whl file.... To install an offline package, run `pip install -U C:\path\filename.whl` in your terminal

**Comment by Erotemic** [comment]
If anyone with experience in CI-wheel building for windows and mac would like to contribute, I could use some help with this. 

I don't have a great process for building and publishing osx / windows wheels on pypi.
