### ISSUE TITLE
NameError: name 'profile' is not defined

### ISSUE THREAD

**Issue by GoingMyWay** [pyutils/line_profiler#154]
I tried to run the code with `kernprof -l -v main.py`. I also add `@profile` to one of the functions, however, it shows returned the error: `NameError: name 'profile' is not defined`.  It seems weird to see it.

**Comment by GoingMyWay** [comment]
Solved via following this post: https://github.com/rkern/line_profiler/issues/35

**Comment by data-djinn** [comment]
seems like this should be added to the docs

**Comment by Erotemic** [comment]
@data-djinn What specifically? Using:

```
import line_profiler
profile = line_profiler.LineProfiler()
```
?
That shouldn't be necessary when using kernprof. (Although you can use that outside of kernprof just fine)

As a MWE I just did: 


```python
# --- main.py
@profile
def foo():
    print(1)

foo()
```

And executed: `kernprof -l -v main.py` and that correctly displays:

```
Wrote profile results to main.py.lprof
Timer unit: 1e-06 s

Total time: 1.2e-05 s
File: main.py
Function: foo at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     1                                           @profile
     2                                           def foo():
     3         1         12.0     12.0    100.0      print(1)
```
