### ISSUE TITLE
It does not work for Python 3.9

### ISSUE THREAD

**Issue by GoingMyWay** [pyutils/line_profiler#155]
I followed this post by using line_profier without magic. However,  when I tried to get the stats via `python -m line_profiler main.py.lprof`, it shows nothing but the following content

```
Timer unit: 1e-06 s
```

My current python3.9 and the system is Ubuntu 20.

Besides that, with magic, it shows `profile not found!`.

**Comment by Erotemic** [comment]
Can you provide a mwe that demonstrates the failure?
