### ISSUE TITLE
Support 3.11, Handle PyFrameObject changes

### ISSUE THREAD

**Issue by Erotemic** [pyutils/line_profiler#164]
As noted in #157, line_profiler is broken by 3.11's changes to PyFrameObject.

I'll list some references on the change:

https://bugs.python.org/issue46836
https://github.com/yaml/pyyaml/issues/630

I don't see a way to immediately fix it. I could use some help.

**Comment by rodja** [comment]
It looks like this will be fixed by pull-request #165. But somehow the work there got stale in the last month...

**Comment by Erotemic** [comment]
We should not wait for the work in #165 to be complete. I would really appreciate any PR that simply adds 3.11 support and nothing else. I tried in: https://github.com/pyutils/line_profiler/pull/173 but apparently I missed something. I unfortunately don't have a lot of time to develop on this, but I will merge and release a patch if someone else can get it working.

**Comment by Erotemic** [comment]
#165 was merged. 311 wheels are on pypi.
