### ISSUE TITLE
Profiling a decorated function

### ISSUE THREAD

**Issue by lagru** [pyutils/line_profiler#167]
In https://github.com/scikit-image/scikit-image/issues/6499 we noticed that using `LineProfiler().add_function(decorated_func)` on a decorated function will trace the decorator and not the decorated function. While this may not necessarily be a bug on line_profiler's side we are still interested in discussing how to best approach this.

**Comment by lagru** [comment]
As @jni suggest's a solution might be to react to the presence of a `__wrapped__` attribute on the function itself. A warning that suggests a solution might go a long way in alleviating this edge case already.

**Comment by Erotemic** [comment]
I like the idea. A good place to start would be to simply introduce the warning.

**Comment by Erotemic** [comment]
Completed.

**Comment by jni** [comment]
Yay! Thank you @Erotemic! I love it when these long-running issues pop up in my notifications with a fix. 🥰
