### ISSUE TITLE
Documentation is bloated and requires too much reading

### ISSUE THREAD

**Issue by kevinlinxc** [pyutils/line_profiler#174]
Title. 

I've referred several people to this repository and they always come back confused.

From my understanding, all you need for a quick start is:

- `pip install line_profiler`
- add `@profile` to a function in script.py
- run `kernprof -lv script.py`

The documentation takes hundreds of words to describe this, and even mixes the order of the last two and doesn't treat the -v view option as default. Why would I, the average Python developer care about the lprof file? I just want to know how slow my function is. Make what most people need front and center, and put the advanced usage below that.

**Comment by Erotemic** [comment]
I would merge a PR that improves the docs.

**Comment by BrianPugh** [comment]
Created a PR that outlines these 3 major steps.
