### ISSUE TITLE
kernprof is not installed

### ISSUE THREAD

**Issue by Jakobhenningjensen** [pyutils/line_profiler#18]
I have installed line-profiler using the git repo i.e not using pip (since I cannot make it work - I have tried installing Visual Studio 2017/2019 and several other things).

After the installation `kernprof` is not installed, i.e the command `kernprof` cannot be run.

**Comment by jdevoldere** [comment]
Same on Linux Mint using pip:
`NameError: name 'kernprof' is not defined`

**Comment by Erotemic** [comment]
@Jakobhenningjensen Recent versions of `line_profiler` after 3.3.0 should now work with pip in windows systems. 

@jdevoldere What version of Python, pip, and line_profiler are causing these symptoms?
