### ISSUE TITLE
Missing `sdist` on PyPI

### ISSUE THREAD

**Issue by shadchin** [pyutils/line_profiler#186]
Looks like release `4.0.1` didn't include `sdist` on PyPI. Would it be possible to push `sdist` for these releases?

**Comment by Erotemic** [comment]
It should have been, I believe we build it. I'll look into it.

**Comment by Erotemic** [comment]
I see the bug. The publish script expects the sdist in dist, but it lives in wheelhouse.

**Comment by Erotemic** [comment]
I manually uploaded the sdist for 4.0.1, hope that helps.

**Comment by shadchin** [comment]
Thank you very much
