### ISSUE TITLE
co_code is malformed

### ISSUE THREAD

**Issue by notEvil** [pyutils/line_profiler#232]
Hi,

can someone confirm the following test case failing with `ValueError: code: co_code is malformed` (Python 3.11.3 on Arch x86_64)

```python
def test_duplicate_function():
    class C:
        def f1(self):
            pass

        def f2(self):
            pass

        def f3(self):
            pass

    profile = LineProfiler()
    profile(C.f1)
    profile(C.f2)
    profile(C.f3)
```

This fixes it

```diff
diff --git a/line_profiler/_line_profiler.pyx b/line_profiler/_line_profiler.pyx
index f83c5b8..0b3399f 100644
--- a/line_profiler/_line_profiler.pyx
+++ b/line_profiler/_line_profiler.pyx
@@ -225,7 +225,7 @@ cdef class LineProfiler:
         if code.co_code in self.dupes_map:
             self.dupes_map[code.co_code] += [code]
             # code hash already exists, so there must be a duplicate function. add no-op
-            co_code = code.co_code + (9).to_bytes(1, byteorder=byteorder) * (len(self.dupes_map[code.co_code]))
+            co_code = code.co_code + (9).to_bytes(1, byteorder=byteorder) * (len(self.dupes_map[code.co_code]) * 2)
             CodeType = type(code)
             code = _code_replace(func, co_code=co_code)
             try:
```

No clue why

**Comment by Erotemic** [comment]
This is because there is a bug when multiple profiled functions contain the same code. Not sure if that fix is robust, but I would like to fix this if possible @Theelx

**Comment by Theelx** [comment]
A fix is definitely possible. Let me take a look when I get to my laptop in ~10m.

**Comment by Theelx** [comment]
I can't reproduce this @notEvil. Can you specify the exact code used (including imports), the command used to run the test, and the error that was raised?

**Comment by Erotemic** [comment]
I can reproduce this by running the following in IPython or via `python <scriptname>`:

```python
def test_duplicate_function():
    import line_profiler

    class C:
        def f1(self):
            pass

        def f2(self):
            pass

        def f3(self):
            pass

    profile = line_profiler.LineProfiler()
    profile(C.f1)
    profile(C.f2)
    profile(C.f3)


if __name__ == '__main__':
    test_duplicate_function()
```

```
Traceback (most recent call last):
  File "/home/joncrall/code/watch/foo.py", line 21, in <module>
    test_duplicate_function()
  File "/home/joncrall/code/watch/foo.py", line 17, in test_duplicate_function
    profile(C.f3)
  File "/home/joncrall/code/line_profiler/line_profiler/line_profiler.py", line 55, in __call__
    self.add_function(func)
  File "line_profiler/_line_profiler.pyx", line 199, in line_profiler._line_profiler.LineProfiler.add_function
  File "line_profiler/_line_profiler.pyx", line 224, in line_profiler._line_profiler.LineProfiler.add_function
  File "line_profiler/_line_profiler.pyx", line 127, in line_profiler._line_profiler._code_replace
ValueError: code: co_code is malformed
```

Tested on the `main` branch and on 4.0.3

**Comment by notEvil** [comment]
> FWIW, I'm using Ubuntu 22.04 with Linux 6.4.9 on x86_64, and I pasted the code provided into tests/test_line_profiler.py then ran py.test.

I put the function in the same place and ran
```
pipenv --rm
pipenv run pip install -e .
pipenv run pip install -r ./requirements/tests.txt
pipenv run python ./run_tests.py
```

**Comment by Theelx** [comment]
Got it, I can reproduce this now. I'm going to see if the patch you posted breaks earlier versions of python though, and if it does then the only thing needed is to add a version check.

**Comment by Theelx** [comment]
Ok, this patch works on 3.8, 3.9, and 3.10. I believe this was a latent bug that I forgot to test for, as it states [in the dis docs](https://docs.python.org/3/library/dis.html) that each bytecode instruction (including no-op) takes 2 bytes, and my code was only adding 1 byte of no-op per duplicate function. I believe 3.11's bytecode caching and adaptive bytecode required some machinery to ensure that co_code was formed correctly, and that addition seems to have caught the code I wrote.

Thanks so much for finding and fixing this @notEvil! Now we just need to submit a PR.
