### ISSUE TITLE
Request for Updating line_profiler Module to Support Python 3.12

### ISSUE THREAD

**Issue by geometry88** [pyutils/line_profiler#247]
We are using the line_profiler module extensively for code profiling in our project.
With the recent update to Python 3.12, we've found that the module is no longer compatible, causing development and debugging to become cumbersome.
Is there a plan to update the module for compatibility with Python 3.12?

**Comment by Theelx** [comment]
I hope to find time to implement 3.12 compatibility in the near future (before January), but it may be difficult depending on my schedule for college classes.

**Comment by Erotemic** [comment]
I did attempt to do it, but I was running into issues. If you can help please see: https://github.com/pyutils/line_profiler/pull/246

**Comment by ianozsvald** [comment]
I'm going to start work on the next edition of our O'Reilly High Performance Python book (best seller for folk wanting faster Python!), for this 3rd edition we're planning on using Python 3.12. I ran into this today as I tried to update my old benchmarks. I'd also love to see Python 3.12 support if possible. Many thanks for your support for this wonderful and very useful project.

**Comment by Erotemic** [comment]
Any help determening why tests are failing in #246 and what the fixes are would be much appreciated. I'm currently stumped.

**Comment by Erotemic** [comment]
New release is out and should support 3.12.
