### ISSUE TITLE
Missing wheels for Mac ARM64

### ISSUE THREAD

**Issue by finsberg** [pyutils/line_profiler#250]
In the latest release on pypi it seems like you forgot to upload wheels for Mac ARM64. Would be great to get this for the next release.

**Comment by Erotemic** [comment]
Is it an artifact produced by github actions that didn't upload, or is it something that needs to added to the actions architecture?

The github action files in this repo are autogenerated, the relevant place to add information about new platforms for binary wheels is here: https://github.com/Erotemic/xcookie/blob/main/xcookie/builders/github_actions.py#L534

**Comment by finsberg** [comment]
Thanks for a swift response. 

You are missing the wheels for `line_profiler-<version>-cpX-cpX-macosx_11_0_arm64.whl` (and also ``line_profiler-<version>-cpX-cpX-manylinux_2_17_aarch64.manylinux2014_aarch64.whl` which would be what you need when running docker on Mac M1).

It is a bit hard for me to pinpoint where in the github actions script you would need to make a change. Perhaps you need to add some config to the `pyproject.toml`?

**Comment by Erotemic** [comment]
Looks like cibuildwheel supports cross compiling arm64 wheels for osx

https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon

I'll see what I can do to add it.

**Comment by Erotemic** [comment]
The new release should have them. Try it out and let me know if it works.

**Comment by finsberg** [comment]
> The new release should have them. Try it out and let me know if it works.

Thanks a lot! Works perfectly
