### ISSUE TITLE
credit for usage

### ISSUE THREAD

**Issue by vibss2397** [pyutils/line_profiler#27]
I am currently using prof.print_stats() in my script, but i want to directly store these, so i am writing a function which uses code inside print_stats() function( show_text(), show_func() ), I was wondering how,if i modify these functions, do i give credit or do i even give credit.

**Comment by artemisart** [comment]
@vibss2397 You can give credit with a comment linking to https://github.com/pyutils/line_profiler

**Comment by Erotemic** [comment]
I wouldn't perseverate too much about reusing snippets of code. However, I do think its often valuable to keep some record indicating what your ideas are inspired by. Typically in my code I'll include a "References" section in the docstring as such. 

```python
def my_custom_print_stats():
    """
    My custom function that does cool stuff. Modified from [1]_.

    References:
      .. [1] https://github.com/pyutils/line_profiler
    """
    do_cool_stuff()
```

**Comment by vibss2397** [comment]
ohh, okay got that. Thanks 👍
