### ISSUE TITLE
Need info in the case of line profiler as a custom decorator for dynamic profiling

### ISSUE THREAD

**Issue by eswarthammana** [pyutils/line_profiler#281]
windows 10
python 3.11
line_profiler 4.1.3

Hi Team, thanks for the tool, I was trying a sample with Django application to profile the complete functions (individual functions and methods with in the class.)

custom profiler decorator, do we have any functions in line_profiler that achieve? and also while i am performing with static methods i am facing a challenge that, expected arguments were 1 but 2 were given.

Do you have any suggestions that I can modify the code to support static methods. Thanks for your time

**Comment by Erotemic** [comment]
You might want to look into the "autoprofile" feature, which adds profile decorators (statically via AST transforms, before the code is even executed). It doesn't have this CSV feature, but you might not want to perform that for every function as it will add a lot of overhead, instead it might be better to collect all of this information from a single profiling object at the end of the script.

**Comment by eswarthammana** [comment]
@Erotemic Thanks for the update.
I tried a sample with autoprofile mode, but the results are not promising.

Below is the class to apply profiling
```
import os

# Example class to test
class TestClass1:
    
    def __init__(self):
        self.stst = self.records()

    @staticmethod
    def records():
        print("I am also there")

    @staticmethod
    def records2():
        print("I am also there 2")

    def records3(self):
        print("I am also there 3")

def test_class1():
    print("test class1 called")
```

below is the code for main execution 

```
from test_class1 import TestClass1

test_clz = TestClass1()
TestClass1.records2()
```

following is the output 

> (profiling_stats) C:\xxxxx\AI\profiling>kernprof -lv -p test_class1.py test1.py       
> I am also there
> I am also there 2
> Wrote profile results to test1.py.lprof
> Timer unit: 1e-06 s
> 
> Total time: 0.0002297 s
> File: C:\xxxxx\AI\profiling\test_class1.py
> Function: __init__ at line 5
> 
> Line #      Hits         Time  Per Hit   % Time  Line Contents
> ==============================================================
>      5                                               def __init__(self):
>      6         1        229.7    229.7    100.0          self.stst = self.records()
> 
> Total time: 0 s
> File: C:\xxxxx\AI\profiling\test_class1.py
> Function: records3 at line 16
> 
> Line #      Hits         Time  Per Hit   % Time  Line Contents
> ==============================================================
>     16                                               def records3(self):
>     17                                                   print("I am also there 3")

I having modified the my code to AST, thanks for the hint. 

> It doesn't have this CSV feature, but you might not want to perform that for every function as it will add a lot of overhead, instead it might be better to collect all of this information from a single profiling object at the end of the script.

Yes, i agree with you.
