### ISSUE TITLE
Improve versioning - Looking for ideas / proposals 

### ISSUE THREAD

**Issue by Erotemic** [pyutils/line_profiler#36]
Currently the `__version__` attribute is hard coded into [line_profiler/line_profiler.py](https://github.com/pyutils/line_profiler/blob/9eecc3d/line_profiler/line_profiler.py#L5) and must be manually updated. 

On one hand I really like having `__version__` be a statically parsable hard-coded value, especially in released versions of the code. But on the other hand, it makes maintenance tricky. I've seen other code bases where a `version.py` file is generated and may depend on the particular git commit for a non-release version. 

I'm looking for proposals / ideas on best practices for ensuring the `__version__` attribute stays consistent both in development and in releases. 

My current thought it perhaps we use a hybrid of the techniques where a hard coded version still exists, but an auto-generated version is also created and the hard-coded version is checked for consistency against the auto-generated one to prevent errors. This scheme might first check to see if we are running a git-installed version, if the current branch is release then the hard-coded version attribute is used as-is while also being checked for consistency. If the branch is master/main, the version gets tagged as a release candidate, and all other branches get versions based on the master/main base and the commit id. 

What do other's think? Does anyone have experience with this / can point to a repo that handles it really well?

**Comment by btjanaka** [comment]
Don't have much experience in this, but I have heard of tools like [bump2version](https://pypi.org/project/bump2version/) and [versioneer](https://github.com/python-versioneer/python-versioneer) that may serve your purpose. I believe bump2version just does a search-and-replace and then creates a commit with a version tag (perhaps it can be configured to add the git commit?). I think Versioneer might do something with Git commits.

**Comment by Erotemic** [comment]
Possible candidate: https://github.com/pypa/setuptools_scm

**Comment by Erotemic** [comment]
I'm not planning on doing anything with this in the near future. Closing the issue for now.
