### ISSUE TITLE
Is it possible to use line profiler with multiple MPI processes?

### ISSUE THREAD

**Issue by rvinaybharadwaj** [pyutils/line_profiler#38]
I am trying to use line profiler with an MPI code and my run script looks like:
```
mpirun -np 2 kernprof -l <python_code.py>
```
However, I end up with *.lprof file for only process 0. Is there a way to get profile information for every process?
Thanks!

**Comment by Erotemic** [comment]
I'm not sure what the dynamics are here. 

I haven't used mpi before, but when I use multiprocessing, I don't get any line_profiler output from anything other than the main process. 

Is there a use-case where you must be in the mpi context to get useful profiling information? My instinct is that it's best to profile blocks of code in a standalone way.

**Comment by rvinaybharadwaj** [comment]
I have a code in which processes handle different tasks, so I was trying to profile in the MPI context. I can use other HPC profilers for MPI, but I like line profiler to get higher level information instead of manually instrumenting the code.

**Comment by Erotemic** [comment]
I've written a few wrappers around line_profiler that execute and output it directly without needing to mess with `.lprof` files. 

Perhaps the function [profile_now](https://github.com/Erotemic/xdev/blob/master/xdev/profiler.py#L44) can help you? You can `pip install xdev` and then wrap a call `myfunc(*args, **kwargs)` as so  `xdev.profile_now(myfunc)(*args, **kwargs)`. I'm wondering if directly creating the `LineProfiler` instance would get around your issue.

**Comment by rvinaybharadwaj** [comment]
Directly creating a ```LineProfiler``` instance worked. Thanks for your help!
