### ISSUE TITLE
License file missing from 3.2.0 sdist

### ISSUE THREAD

**Issue by jakirkham** [pyutils/line_profiler#51]
The recently release sdist on PyPI does not appear to ship the license file with it

Edit: One way to fix this would be to use [`license_files` in the `setup` function]( https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html?highlight=license_files#metadata ) to package all of these

**Comment by Erotemic** [comment]
Thanks for the report. I made  #52 which fixes this.

This wasn't breaking anything functionality wise was it? Or did you just notice the files were missing?

**Comment by jakirkham** [comment]
In conda-forge we repackage the license file in the Conda package. This release failed with build errors due to the missing license. Hence the issue
