### ISSUE TITLE
Windows wheels

### ISSUE THREAD

**Issue by cliffckerr** [pyutils/line_profiler#53]
One of my colleagues discovered "unofficial" Windows wheels for line_profiler, which appear to work:

https://www.lfd.uci.edu/~gohlke/pythonlibs/#line_profiler

Is it possible to make these part of the official release? (Or, more reasonably, use the same method to build the Windows wheels.) I see https://github.com/pyutils/line_profiler/pull/6 so I appreciate that this is not a trivial problem to solve, but am hopeful that if someone else has done it then it should be doable at least in theory!

**Comment by Erotemic** [comment]
Christoph Gohlke is a wizard, and I have no idea how he does it. 

I've released a windows wheel before, and it was a nightmare. The method probably doesn't work anymore. From what I remember it was based on this: https://github.com/matthew-brett/multibuild

I simply don't have the time (or emotional energy) to deal with all the quirks of win32, but I would love to add support for it, but I would need help.

**Comment by Erotemic** [comment]
You might also be interested in: https://pypi.org/project/gohlkegrabber/

**Comment by Erotemic** [comment]
Fixed by #76
