### ISSUE TITLE
how to install line-profiler on m1?

### ISSUE THREAD

**Issue by shyzz** [pyutils/line_profiler#58]
i  install cmake, scikit-build,Cython,ninja. then `cd line_profiler & python setup.py install` . its no working. it also raise ` ERROR: Could not build wheels for cmake, ninja which use PEP 517 and cannot be installed directly`.

**Comment by Erotemic** [comment]
In a fresh clone of `line_profiler`, what is the output of: 

```
python setup.py build --verbose
```

**Comment by Erotemic** [comment]
It would be nice to have a binary for M1. If anyone knows how to do this with cibuildwheel and github actions, please either submit a PR or respond with resources on how to do it.

**Comment by ChenZhongPu** [comment]
Surprisingly, I tried `pip install line_profiler` on my Mac with M1 chip, and it works! So I think the x86-64 package is compatible through Rosetta2.

**Comment by Erotemic** [comment]
As of version 4.1.3, arm64 wheels should be available for osx on pypi.
