### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [pyutils/line_profiler#62]
Problem
---------
On aarch64, ‘pip install line-profiler’  builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install line-profiler’  should download the wheels from pypi

@Erotemic Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by Erotemic** [comment]
Very interested. I simply don't have much experience with anything outside x86_64.

**Comment by Erotemic** [comment]
Fixed by #76
