### ISSUE TITLE
Coverage is still not working

### ISSUE THREAD

**Issue by Erotemic** [pyutils/line_profiler#65]
I recently merged #11 which does seem to successfully upload a .coverage file to codecov.io, and it does receive it, but there seems to be an issue with displaying it? The coverage is reported via the terminal in every CI run, so we do measure the coverage (currently at ~43% modulo issues where we the global lines have issues being measured correctly). 

But on the website I see nothing and no indication of what the error is: 

https://codecov.io/github/pyutils/line_profiler/

Any help is appreciated.

**Comment by s-weigand** [comment]
I think the problem is that the [python client needs token](https://github.com/codecov/codecov-python#ci-providers) even for public repos. The [gh-action](https://github.com/codecov/codecov-action#arguments) works without a token for public repos.
