### ISSUE TITLE
ModuleNotFoundError: No module named 'line_profiler._line_profiler'

### ISSUE THREAD

**Issue by ICYPOLE** [pyutils/line_profiler#66]
OS: win10
Python: 3.6.8 64-bit
line_profiler: version 3.2.1

```python
# trial.py
@profile
def func():
    for i in range(10):
        print('hello world')

func()
```
When run the above code with `kernprof -l .\trial.py`, error occurs:

File "c:\users\a\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\a\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\A\AppData\Local\Programs\Python\Python36\Scripts\kernprof.exe\__main__.py", line 9, in <module>
  File "c:\users\a\appdata\local\programs\python\python36\lib\site-packages\kernprof.py", line 211, in main
    import line_profiler
  File "c:\users\a\appdata\local\programs\python\python36\lib\site-packages\line_profiler\__init__.py", line 10, in <module>
    from .line_profiler import __version__
  File "c:\users\a\appdata\local\programs\python\python36\lib\site-packages\line_profiler\line_profiler.py", line 26, in <module>
    from ._line_profiler import LineProfiler as CLineProfiler
ModuleNotFoundError: No module named 'line_profiler._line_profiler'

**Comment by Erotemic** [comment]
I think I see the root of this issue. Inside of kernprof we imported line_profiler to get the version, but if the C-extension module was not built, then it raises a ModuleNotFoundError. I'm not sure why ImportError isn't catching it, but it should have fallen back on an "UNKNOWN version". 

I'll release a patch that has a more graceful kernprof fallback, and also gives a better line_profiler error message.

**Comment by Erotemic** [comment]
I'm not sure how this is happening because ModuleNotFoundError inherits from ImportError, which should be caught when `from line_profiler import __version__` fails due to the c-extension module not being compiled.

I did starts #67 which currently adds a more verbose error message when the `line_profiler._line_profiler` module hasn't been complied, but I'm perplexed as to how you are getting this error with 3.6. I tried to reproduce it, but invoking kernprof without compiling `line_profiler._line_profiler` gracefully fails on my machine.

**Comment by ICYPOLE** [comment]
> I think I see the root of this issue. Inside of kernprof we imported line_profiler to get the version, but if the C-extension module was not built, then it raises a ModuleNotFoundError. I'm not sure why ImportError isn't catching it, but it should have fallen back on an "UNKNOWN version".
> 
> I'll release a patch that has a more graceful kernprof fallback, and also gives a better line_profiler error message.

How to build C-extension module so as to run line_profiler normally? I am not clear where can I find the solution in the installation manual.

**Comment by Erotemic** [comment]
Ideally you should be able to checkout the repo, cd into it and then `pip install .` or `pip install -e .` and scikit-build will correctly find your compiler and build the executable. On linux this works reasonably well. On other systems, I don't have a lot of experience. 

If you are using windows you can always use Christoph Gohlke's packages: https://www.lfd.uci.edu/~gohlke/pythonlibs/#line_profiler

But if you are only using `kernprof.py` then you should not need to compile anything. If you look at the code in kernprof: https://github.com/pyutils/line_profiler/blob/master/kernprof.py#L11 it does try to import `line_profiler` but only to grab the version. If the c-extension isn't compiled it should raise a ModuleNotFoundError, which should be caught by the ImportError on line 13, so I don't understand why your version isn't catching that.

**Comment by s-weigand** [comment]
Alternatively, there are also binaries on [conda-forge](https://github.com/conda-forge/line_profiler-feedstock), [up to version 3.1.0](https://anaconda.org/conda-forge/line_profiler). But for the newer versions, their pipeline seems to be broken with the same error.

Anyway, yesterday I stumbled about the same error and it would be nice to also have all kinds on wheels on pip.
So I fiddled a bit around with the action for [joerick/cibuildwheel](https://github.com/joerick/cibuildwheel) and managed to create a [workflow building all kinds of wheels](https://github.com/s-weigand/line_profiler/actions/runs/785093565).

The only ones it didn't manage to build were `pp*`, `*manylinux_ppc64le` and `*manylinux_s390x`.

<details>
<summary>
Built files
</summary>

```console
$ ls -la dist
total 2488
drwxr-xr-x  2 runner docker  4096 Apr 26 10:01 .
drwxr-xr-x 11 runner docker  4096 Apr 26 10:01 ..
-rw-r--r--  1 runner docker 52388 Apr 26 10:01 line_profiler-3.2.1+40127761-cp35-cp35m-macosx_10_9_x86_64.whl
-rw-r--r--  1 runner docker 64713 Apr 26 10:01 line_profiler-3.2.1+40127761-cp35-cp35m-manylinux1_i686.whl
-rw-r--r--  1 runner docker 63025 Apr 26 10:01 line_profiler-3.2.1+40127761-cp35-cp35m-manylinux1_x86_64.whl
-rw-r--r--  1 runner docker 64716 Apr 26 10:01 line_profiler-3.2.1+40127761-cp35-cp35m-manylinux2010_i686.whl
-rw-r--r--  1 runner docker 63027 Apr 26 10:01 line_profiler-3.2.1+40127761-cp35-cp35m-manylinux2010_x86_64.whl
-rw-r--r--  1 runner docker 64937 Apr 26 10:01 line_profiler-3.2.1+40127761-cp35-cp35m-manylinux2014_aarch64.whl
-rw-r--r--  1 runner docker 46796 Apr 26 10:01 line_profiler-3.2.1+40127761-cp35-cp35m-win32.whl
-rw-r--r--  1 runner docker 51035 Apr 26 10:01 line_profiler-3.2.1+40127761-cp35-cp35m-win_amd64.whl
-rw-r--r--  1 runner docker 53839 Apr 26 10:01 line_profiler-3.2.1+40127761-cp36-cp36m-macosx_10_9_x86_64.whl
-rw-r--r--  1 runner docker 66219 Apr 26 10:01 line_profiler-3.2.1+40127761-cp36-cp36m-manylinux1_i686.whl
-rw-r--r--  1 runner docker 64692 Apr 26 10:01 line_profiler-3.2.1+40127761-cp36-cp36m-manylinux1_x86_64.whl
-rw-r--r--  1 runner docker 66223 Apr 26 10:01 line_profiler-3.2.1+40127761-cp36-cp36m-manylinux2010_i686.whl
-rw-r--r--  1 runner docker 64695 Apr 26 10:01 line_profiler-3.2.1+40127761-cp36-cp36m-manylinux2010_x86_64.whl
-rw-r--r--  1 runner docker 65697 Apr 26 10:01 line_profiler-3.2.1+40127761-cp36-cp36m-manylinux2014_aarch64.whl
-rw-r--r--  1 runner docker 47363 Apr 26 10:01 line_profiler-3.2.1+40127761-cp36-cp36m-win32.whl
-rw-r--r--  1 runner docker 51575 Apr 26 10:01 line_profiler-3.2.1+40127761-cp36-cp36m-win_amd64.whl
-rw-r--r--  1 runner docker 52506 Apr 26 10:01 line_profiler-3.2.1+40127761-cp37-cp37m-macosx_10_9_x86_64.whl
-rw-r--r--  1 runner docker 65341 Apr 26 10:01 line_profiler-3.2.1+40127761-cp37-cp37m-manylinux1_i686.whl
-rw-r--r--  1 runner docker 64124 Apr 26 10:01 line_profiler-3.2.1+40127761-cp37-cp37m-manylinux1_x86_64.whl
-rw-r--r--  1 runner docker 65345 Apr 26 10:01 line_profiler-3.2.1+40127761-cp37-cp37m-manylinux2010_i686.whl
-rw-r--r--  1 runner docker 64128 Apr 26 10:01 line_profiler-3.2.1+40127761-cp37-cp37m-manylinux2010_x86_64.whl
-rw-r--r--  1 runner docker 65388 Apr 26 10:01 line_profiler-3.2.1+40127761-cp37-cp37m-manylinux2014_aarch64.whl
-rw-r--r--  1 runner docker 47387 Apr 26 10:01 line_profiler-3.2.1+40127761-cp37-cp37m-win32.whl
-rw-r--r--  1 runner docker 51382 Apr 26 10:01 line_profiler-3.2.1+40127761-cp37-cp37m-win_amd64.whl
-rw-r--r--  1 runner docker 53267 Apr 26 10:01 line_profiler-3.2.1+40127761-cp38-cp38-macosx_10_9_x86_64.whl
-rw-r--r--  1 runner docker 67482 Apr 26 10:01 line_profiler-3.2.1+40127761-cp38-cp38-manylinux1_i686.whl
-rw-r--r--  1 runner docker 66251 Apr 26 10:01 line_profiler-3.2.1+40127761-cp38-cp38-manylinux1_x86_64.whl
-rw-r--r--  1 runner docker 67485 Apr 26 10:01 line_profiler-3.2.1+40127761-cp38-cp38-manylinux2010_i686.whl
-rw-r--r--  1 runner docker 66248 Apr 26 10:01 line_profiler-3.2.1+40127761-cp38-cp38-manylinux2010_x86_64.whl
-rw-r--r--  1 runner docker 68136 Apr 26 10:01 line_profiler-3.2.1+40127761-cp38-cp38-manylinux2014_aarch64.whl
-rw-r--r--  1 runner docker 47935 Apr 26 10:01 line_profiler-3.2.1+40127761-cp38-cp38-win32.whl
-rw-r--r--  1 runner docker 52352 Apr 26 10:01 line_profiler-3.2.1+40127761-cp38-cp38-win_amd64.whl
-rw-r--r--  1 runner docker 53410 Apr 26 10:01 line_profiler-3.2.1+40127761-cp39-cp39-macosx_10_9_x86_64.whl
-rw-r--r--  1 runner docker 67684 Apr 26 10:01 line_profiler-3.2.1+40127761-cp39-cp39-manylinux1_i686.whl
-rw-r--r--  1 runner docker 66316 Apr 26 10:01 line_profiler-3.2.1+40127761-cp39-cp39-manylinux1_x86_64.whl
-rw-r--r--  1 runner docker 67686 Apr 26 10:01 line_profiler-3.2.1+40127761-cp39-cp39-manylinux2010_i686.whl
-rw-r--r--  1 runner docker 66320 Apr 26 10:01 line_profiler-3.2.1+40127761-cp39-cp39-manylinux2010_x86_64.whl
-rw-r--r--  1 runner docker 68147 Apr 26 10:01 line_profiler-3.2.1+40127761-cp39-cp39-manylinux2014_aarch64.whl
-rw-r--r--  1 runner docker 48125 Apr 26 10:01 line_profiler-3.2.1+40127761-cp39-cp39-win32.whl
-rw-r--r--  1 runner docker 52283 Apr 26 10:01 line_profiler-3.2.1+40127761-cp39-cp39-win_amd64.whl
-rw-r--r--  1 runner docker 53626 Apr 26 10:01 line_profiler-3.2.1+40127761.tar.gz
```
</details>

Since `cibuildwheel` also tests the built wheels `python-publish.yml` and `python-test.yml` could even be a single workflow where deployment is only triggered at different events (e.g. `publish` or `tag`).

If you want I could clean up my code a bit and make it a PR. 😄

**Comment by Erotemic** [comment]
I think a lot of this boils down to a mistake that I made where I wanted kernprof to import line_profiler so their version information could be tied together. I think this is causing these side effects. I took that out in #67 so kernprof should now work without having line-profiler compiled.

@s-weigand It would be amazing if you could make a PR so the CI builds and tests the windows and osx wheels.

**Comment by futurulus** [comment]
Looks like this is well on its way to getting fixed, but in the meantime, downgrading to 3.1.0 was an effective workaround for me. (I'm running it on a conda-based Python, but the installation and subsequent downgrade were both done with ordinary `pip`, so I'd expect this to work for others not using Conda too.)

**Comment by Erotemic** [comment]
I just released 3.2.2 which just decouples kernprof and line_profiler. Can people here verify that it fixes the issue?

**Comment by jakirkham** [comment]
We are actually seeing this in conda-forge. Have been building the C extension with past versions, but this issue started showing up with 3.2.0. Not seeing any error in the build outside of this `import` at the end, but maybe we are missing something.

Here's the 3.2.2 PR ( https://github.com/conda-forge/line_profiler-feedstock/pull/41 ) w/CI. Maybe someone can spot if we are doing something wrong here or we can try fixes as well

**Comment by futurulus** [comment]
I get this when using 3.2.2 (where `[venv]` is a redacted path on my machine):
```
$ kernprof -l profile.py 
Traceback (most recent call last):
  File "[venv]/lib/python3.7/site-packages/line_profiler/line_profiler.py", line 27, in <module>
    from ._line_profiler import LineProfiler as CLineProfiler
ModuleNotFoundError: No module named 'line_profiler._line_profiler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[venv]/bin/kernprof", line 8, in <module>
    sys.exit(main())
  File "[venv]/lib/python3.7/site-packages/kernprof.py", line 210, in main
    import line_profiler
  File "[venv]/lib/python3.7/site-packages/line_profiler/__init__.py", line 10, in <module>
    from .line_profiler import __version__
  File "[venv]/lib/python3.7/site-packages/line_profiler/line_profiler.py", line 31, in <module>
    'been compiled. ex={!r}'.format(ex)
ModuleNotFoundError: The line_profiler._line_profiler c-extension module has not been compiled. ex=ModuleNotFoundError("No module named 'line_profiler._line_profiler'")
```

**Comment by Erotemic** [comment]
@futurulus try `pip install line_profiler -U` to upgrade to the latest version. That issue has now been mitigated.

**Comment by futurulus** [comment]
👍 Working for me now in 3.2.6, thank you!
