### ISSUE TITLE
Wrong IPython version in requirements/runtime.txt for Python 3.6

### ISSUE THREAD

**Issue by maxocub** [pyutils/line_profiler#77]
Hi,
I think there is a typo in requirements/runtime.txt :
`IPython >=0.13, <=7.7.0 ; python_version <= '3.6'`
According to https://github.com/ipython/ipython#overview, it should be :
`IPython >=0.13, <7.17.0 ; python_version <= '3.6'`
Since IPython supprts Python 3.6 up to version 7.17.0.

**Comment by Erotemic** [comment]
I pushed up the new wheels to pypi. There was an issue with uploading automatically via github actions, so I manually downloaded the artifacts and uploaded the wheels in order to avoid repo downtime. Let me know if anything broke.
